
const double PROFILE_IMG_WIDTH = 50;
const double PROFILE_IMG_HEIGHT = 50;
const double FLOATING_BUTTON_WIDTH = 60.0;
const double FLOATING_BUTTON_HEIGHT = 60.0;
const double FLOATING_ICON_SIZE = 46.0;

const double BOTTOM_NAV_ICON_SIZE = 34.0;
const double BOTTOM_NAV_ICON_SIZE_2 = 28.0;

const double TEXT_FORM_FIELD_WIDTH = 240.0;
const double TEXT_FORM_FIELD_HEIGHT = 60.0;

const double TIME_LIST_WIDTH = 60.0;

const double CUSTOM_PAINT_CONTAINER_WIDTH = 300.0;
const double CUSTOM_PAINT_CONTAINER_HEIGHT = 300.0;
const double TIME_AND_EVENT_SECTION_CONTAINER_HEIGHT = 360.0;
const double EVENT_CARD_CONTAINER_HEIGHT = 80.0;
const double EVENT_CARD_CONTAINER_WIDTH = 80.0;
